name: Onboarding Change Doc

on:
  pull_request:
    branches: [main]
    paths:
      - 'config.json'
      - 'policies/api.xml'

permissions:
  contents: read
  pull-requests: read

jobs:
  call-doc-generator:
    if: |
      contains(github.event.pull_request.title, 'Onboarding') ||
      contains(github.event.pull_request.title, 'Deployment')
    uses: ./.github/workflows/reusable-onboarding-change-doc.yaml
