name: Onboarding Change Doc

on:
  pull_request:
    branches: [main]
    paths:
      - 'config.json'
      - 'policies/api.xml'

permissions:
  pull-requests: read 

jobs:
  call-doc-generator:
    uses: ./.github/workflows/reusable-onboarding-change-doc.yaml
