name: Onboarding Change Doc

on:
  pull_request:
    branches: [main]
    paths:
      - 'config.json'
      - 'policies/api.xml'

permissions:
  contents: read
  pull-requests: read

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check PR title
        id: check
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $TITLE"
          if [[ "$TITLE" == *Onboarding* || "$TITLE" == *Deployment* ]]; then
            echo "PR Title matches. Proceeding."
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "ERROR: PR title must contain 'Onboarding' or 'Deployment'."
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  call-doc-generator:
    needs: check-pr-title
    if: needs.check-pr-title.outputs.should_run == 'true'
    uses: ./.github/workflows/reusable-onboarding-change-doc.yaml
