name: Onboarding Change Doc

on:
  pull_request:
    branches: [main]
    paths:
      - 'config.json'
      - 'policies/api.xml'

permissions:
  contents: read
  pull-requests: read

jobs:
  call-doc-generator:
    uses: heidsEm/heidsfromheaven/.github/workflows/reusable-onboarding-change-doc.yaml
