name: Print File Values to DOCX on PR from Production

on:
  pull_request:
    branches:
      - production
    types: [opened, synchronize, reopened]

jobs:
  print-file-value:
    if: |
      contains(github.event.pull_request.body, 'Onboarding') &&
      contains(github.event.pull_request.body, 'deployment')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install python-docx
        run: pip install python-docx

      - name: Generate docx from folder files
        run: |
          python gen_docx.py

      - name: Commit and push output.docx
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output.docx
          git commit -m "Add output.docx with contents of devops-docu" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}